---
title: "Sonido en la mesa del salón"
subtitle: "Trabajo 1"
author: "Ana María López - Juan Carlos López - Wilinton Galeano"
date: "Febrero, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Estructura de Directorios
dir.input  <- 'Data/Trabajo1/'
# Cargar Librerias
library(dplyr)
library(ggplot2)
```

## Lectura de la base de datos

```{r}
# Vector de Datos
distance <- c("0","120","180","240","300","360","480","540","600")

obs <- NULL

for (i in 1:length(distance)){
  obs <- rbind(obs,cbind(read.csv(paste(dir.input,paste("Experimento sin t_tulo Grabaci_n 1_",distance[i],".csv",sep=""),sep="")),distance[i]))
} 
colnames(obs) <- c("timestamp","decibelsource","distance")

```

```{r}
seg <- 15
```



```{r}
obs <- obs %>%
         mutate(date = as.POSIXct(timestamp/1000, origin="1970-01-01"))

```


```{r}
obs_r <- obs %>%
           group_by(distance,tiempo = round(timestamp/(seg * 1000), 0)) %>%
           summarise(Mdecibelsource = mean(decibelsource))
```


```{r}
ggplot(obs_r %>% filter(distance==0), aes(tiempo, Mdecibelsource)) +
  geom_line()
```



```{r}
#library(dplyr)
#cel_120_r <- cel_120 %>%
#           group_by(tiempo = round(timestamp/(segundos * 1000), 0)) %>%
#           summarise(MDecibelSource = mean(DecibelSource))
ggplot(obs_r %>% filter(distance==120), aes(tiempo, Mdecibelsource)) +
  geom_line()
```


```{r}
#library(ggplot2)
ggplot(obs_r %>% filter(distance==120), aes(tiempo, Mdecibelsource-16)) +
  geom_line()
```


```{r}
cel_t <- inner_join(obs_r %>% filter(distance==0), obs_r %>% filter(distance==120), by = "tiempo")
```


```{r}
library(ggplot2)
ggplot(cel_t, aes(Mdecibelsource.x, Mdecibelsource.y)) +
  geom_point()
```


```{r}
with(cel_t, cor(Mdecibelsource.x, Mdecibelsource.y))
```

